//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_Objectives
    {
        public int ObjID { get; set; }
        public Nullable<int> NameID { get; set; }
        public Nullable<double> ObjMinValue { get; set; }
        public Nullable<double> ObjMaxValue { get; set; }
        public bool ObjVal_IsLessThan { get; set; }
        public string FishOrigin { get; set; }
        public bool ProgramAdopted { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<int> ObjVarID { get; set; }
        public bool ObsoleteFlag { get; set; }
        public string Comments { get; set; }
        public string ObjValType { get; set; }
        public string TargetTimeline { get; set; }
    
        public virtual tblName tblName { get; set; }
    }
}
