//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblName
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblName()
        {
            this.LU_Objectives = new HashSet<LU_Objectives>();
        }
    
        public int NameID { get; set; }
        public string RecordType { get; set; }
        public string PrimaryName { get; set; }
        public string AltName1 { get; set; }
        public string AltName2 { get; set; }
        public string AltName3 { get; set; }
        public string ESAStatus { get; set; }
        public string ESAListingYear { get; set; }
        public string Designation { get; set; }
        public string Run { get; set; }
        public int SpeciesID { get; set; }
        public Nullable<int> SN_PopID { get; set; }
        public string PopImageURL { get; set; }
        public Nullable<int> ESUID { get; set; }
        public Nullable<int> MPGID { get; set; }
        public Nullable<int> SubbasinID { get; set; }
        public Nullable<int> RecDomain { get; set; }
        public Nullable<int> RecSubDomain { get; set; }
        public string DistributionLink { get; set; }
        public string CAAbundanceLink { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Archive { get; set; }
        public string PopType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LU_Objectives> LU_Objectives { get; set; }
    }
}
